### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#1]
Do we want to draw design cues (color palette, typography, etc.) from the Processing 2.x world or go for something new for this project?

**Comment by REAS** [comment]
We should do something in the realm of the Processing 2 graphics, but it can certainly deviate. For example, we could give this project a white to make it a little fresher and friendlier. I think we should use the same typographic style.

**Comment by scotthmurray** [comment]
Yes, and related: Scott, you mentioned needing to create a syntax template (maybe not the right word?) for the Ace editor. I'd suggest we carry over the P2.0 syntax color scheme there, so when people download P2.0 later, it is more familiar.

**Comment by scottgarner** [comment]
I agree that the highlighting should match as closely as possible. WIth the latest push it's just using the Java mode in Ace, but it also supports importing language templates from Textmate and Sublime text, so maybe we can find a nice one for Processing without having to start from scratch.

Regarding overall look, for tight projects like this with a few pages, I tend to design and develop in tandem rather than do mock-ups beforehand. Always feel free to jump in and tweak anything or suggest a change because there will certainly be points where everything will look ridiculous.

**Comment by REAS** [comment]
We generate the code highlighting in the PDE through a Perl script we wrote. I haven't looked into the format for Ace highlighting, but I would imagine our original script could be modified to spit out the right thing. Please have a look:

This is our PDE highlight file:
https://github.com/processing/processing/blob/master/java/keywords.txt

This is the base file and the script that generates it:
https://github.com/processing/processing-web/blob/master/generate/keywords_create.cgi
https://github.com/processing/processing-web/blob/master/generate/keywords_base.txt

**Comment by scottgarner** [comment]
I took a stab at using a tool packaged with Ace to convert a [TextMate language template for Processing](https://github.com/peon/processing.tmbundle). At first glance, the results seem pretty good insofar as it highlights the right things. I think this is a good starting point and may actually be all we need.

What isn't covered is the color scheme, which will probably need to be built by hand using the proper color values from Processing.

**Comment by scottgarner** [comment]
Just to return to this with a few comments:

I broke the Ace colorization out into a custom "theme" file for Processing, so we can tweak the editor colors with minimal effort.

Speaking to overall look and feel, I think building on Casey's original comp has gone well so far, though I'm feeling a pretty strong disconnect between the look of the video and the look of the rest of the site. Maybe it's just something as simple as the color temperature of the white board being too warm currently, but I wanted to bring up the idea of restyling the site a bit to live more harmoniously with the video once we have final footage.

I'm not sure this means we need to do anything special for the video footage beyond normal color correction, but I think the final result should be that the neutrals of the site live in the same world as the neutrals of the video.

Also, Dan should probably wear a pink t-shirt to tie everything together.

**Comment by shiffman** [comment]
I met with Jesse yesterday and we are planning to use the brick wall in room 50 at ITP as a backdrop, along with a rolling whiteboard.  So perhaps this will help as it won't be a stark white backdrop?  

Yes, to the pink t-shirt!  I was thinking actually of wearing the new Processing T.

**Comment by scottgarner** [comment]
I've been thinking on this a bit more and have a couple of comments.

1) A little color correction on the current footage worked wonders. A white whiteboard rather than a brownish one lives in the design much better.

![color](https://f.cloud.github.com/assets/786436/1495483/1eee0bac-47eb-11e3-8940-b3ab3dbe7abf.jpg)

2) As for the brick wall, I think that could make for a warmer, nicer video, but footage like that isn't necessarily going to live in our flat, almost-process-color world very well.

I'm not especially attached to the current look and I think it would be relatively easy to pull a new set of colors and possibly textures from the video. However, if we're really wanting to stick with the current flat palette, the brick wall will almost certainly clash a bit.

Just something to think about. My instinct is that if we want the current flat world, we only shoot Dan against white. If we'd rather have a richer video, then the site should reflect that.

**Comment by REAS** [comment]
Yes, that color correction was a great change. I think it makes sense to adapt the site to what works best for the video. For some reason, I like the idea of the brick, that's something I've always liked about ITP. I remember that Ben didn't like the BLUE and I'm not married to it, so it's very open to change.

**Comment by shiffman** [comment]
Wow, amazing what a difference that makes.  As of now, we're going for something quite different than my ITP lesson videos.  We're going to shoot with multiple cameras (wide, close-up, whiteboard close-ups, etc) and the video will be edited.  The intro video will include cutaways to other Processing projects, etc.  So I suppose I'm with Casey, let's just see how the video turns out and try to adapt the site around it.   Hopefully it'll all magically come together!

**Comment by scotthmurray** [comment]
Agreed — make the video great first, then we can adjust the site color palette later.

**Comment by scottgarner** [comment]
Assigning this to myself with the plan to pull a consistent palette from the video or develop a complementary one, though anyone else can take a stab at it. I'll just plan to do the CSS work.

**Comment by scottgarner** [comment]
I made some CSS refinements here and here, but nothing major. Going to call this done for now.
