### ISSUE TITLE
disqus?

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#15]
I am recording test videos this morning and will have them all uploaded shortly.  It just occurred to me that it might be worthwhile to have some feature on the site which allows users to ask a question or communicate with us (and others).  Yes, we have the Processing forum, but maybe this needs its own thing.  Should we have a page with "disqus" comments?

**Comment by scottgarner** [comment]
Hmm. That does seem important, though I'm not sure how to best implement it. I mean, is there a thread per topic, one thread for the whole site, etc. Also, does it live within the interface somehow or on another page?

It's certainly easy to add, I'm just undecided on what's most clear and useful.

**Comment by scotthmurray** [comment]
This is a great idea, but I'd suggest this is lowest priority.

If we do implement it, can we just leverage a system we already have in place?  For example, we could create a couple new threads on the forum, e.g.:
1. Hour of Code Feedback: Share your thoughts!
2. Hour of Code Creations: Share your creations!

Then we can just link out to the forums.  Could be a nice way to transition students into the Processing community, and avoid clogging out pretty page with too much JavaScript. :)

**Comment by scottgarner** [comment]
Maybe this is a good thing to add to the "hints" window at the end of each lesson. We'll already have some additional buttons up there and could add links to discussions, too.

**Comment by shiffman** [comment]
agreed, let's not reinvent and just point people to the forum.

**Comment by shiffman** [comment]
In the video I said that there was a link to the Processing forum.  I think we should add a special forum category for people doing this tutorial.  I also said I would check it and answer questions there .. . and so I shall!  I'll leave this open for now as a reminder.  The link will appear on the goodbye "splash" page (which is something that @scottgarner discussed today)

**Comment by scottgarner** [comment]
I put a placeholder for this in the code. I'll assign it to @REAS just as a reminder to create the category and pass the link to me.

**Comment by scottgarner** [comment]
Bumping this to the next milestone. @REAS, we need something like a "Hello Processing" category in the Processing Forum.

For now I'll link to http://forum.processing.org/two/categories/hello-processing and change it when we have a real link.

**Comment by REAS** [comment]
I made it prematurely, but we are working on this in the open. This is the URL:
http://forum.processing.org/two/categories/hello-processing
