### ISSUE TITLE
Examples vs. my explanations

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#18]
I found that while making the videos I am more inclined to just show simple ideas, like a circle in the center, a rectangle below.  (255,0,0) as red, (0,255,0) as green, etc. The examples prepared by @REAS are a bit more complex and thoughtful in terms of design and color.  How to marry these?   One thought is that I keep the simplicity in my explanations but there are buttons that allow the student to "load" these more "official" examples while experimenting.   Another idea is that at the end of each lesson, I say a wrap-up sentence explaining the example and it loads automatically for the student to begin with.  Maybe that's best.

**Comment by REAS** [comment]
Idea #2 sounds good. I think it's great for the explanations to be as simple as possible and for the examples to have some slightly finer details.

**Comment by scottgarner** [comment]
I think this is a really important point. It seems smart to keep the demos dead simple, but the trade off is that they'll lack a degree of visual appeal that might keep things exciting for a student.

Ending each lesson with a "cool" example seems like a good way to handle this. Beginners might get more satisfaction tweaking something that already looks nice than struggling to make something on their own (though they'll have the option of so inclined).

**Comment by shiffman** [comment]
closing this issue as we will go with idea 2, wrap-up sentence at the end of each section and example will auto load. this is reflected in the script outline:

https://github.com/scottgarner/Processing-Hour-Of-Code/blob/gh-pages/Script.md
