### ISSUE TITLE
direct users to hour of code site when completed

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#19]
http://code.org/api/hour/finish

**Comment by scottgarner** [comment]
Do you think we can put a link in the "hints" section of the last video or should we actively redirect them?

-S

**Comment by shiffman** [comment]
I think this is probably best answered once we've finished with all the other elements.  But yes, a simple solution like that might work.  I think they may prefer an automatic redirect in order to be able to track stats for the tutorials, but we can come back to this later.

**Comment by scottgarner** [comment]
Notes for this are in the code and will be addressed as part of the "hints" section.

**Comment by shiffman** [comment]
I was reading through the hour of code materials and we may want to be a bit more "aggressive" in pushing people back towards their site for their tracking purposes.  Would it be horrible to automatically send users to their "finish" page in a new tab when they complete the goodbye video?  Or when they share?  Maybe the hints is fine.    I am very unsure about this one.

**Comment by scottgarner** [comment]
Tricky. My immediate thought is that doing anything automatic would be jarring since you don't warn them in the video. There's also the problem of doing a window.open without direct user input, which browsers generally see as an attempt to launch popups. We can experiment, but a button seems safest.

**Comment by shiffman** [comment]
Yes, good points.  Maybe we'll just want to include additional links strategically placed, like one on the goodbye page i.e. -- "Register your work with hour of code and receive a completion certificate blah blah blah".  We can worry about this later.

**Comment by shiffman** [comment]
Revisiting this issue.  I added something to hints (needs more thoughtful styling) as well as an addition option to "share", i.e. you can share via Hour of Code.  Perhaps that's not a good idea as it's not actually sharing what you made.  see: b6017112a503fdc9bda3f3c50bce63dc9a92bc5f

**Comment by scottgarner** [comment]
@shiffman, do you have time to chat tomorrow so we can formulate a plan of attack over the break?

**Comment by shiffman** [comment]
Any chance first thing in the morning would work for you 10:00am-ish?  I have office hours appts signed up starting at 10:20.  I should also have a brief window right at 3 after my 12-3 class (have to run at 3:15ish).  I am also available via skype pretty much all day wednesday.

**Comment by scottgarner** [comment]
I have class in the morning, but it's a work session, so I may be able to get away at 10am. If not, I'll see you at 3pm.

**Comment by shiffman** [comment]
@scottgarner and i discussed this and we think that just making this a much more prominent link / banner in the final hints will do the trick.  We'll take it out of the share option.  And also include a permanent link to hour of code in the top navigation.

**Comment by shiffman** [comment]
closing this issue and discussing under the new code.org API one.
