### ISSUE TITLE
Color Browser Features

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#27]
I wanted to make an individual issue for this because it's a lower priority than the rest of the editor issues.

I'm using a plugin called Spectrum in a way it wasn't really designed for, but it works reasonably well. It has an option to show the color that is being selected, but this feature is tied to an option to show the initial color, which currently doesn't work.

The solution is to either modify Spectrum to only show the current color or to throw in some regular expressions to figure out the initial color from the editor and set it. 

The buttons could us some styling work, too, because Bootstrap appears to be doing something strange to them.

**Comment by scottgarner** [comment]
I reworked the color picker to add some nice features, like opening with the current color visible and showing the color update as you pick. I've almost certainly introduced bugs in this process, but I'll close the issue for now.

**Comment by shiffman** [comment]
looks fantastic thanks!
