### ISSUE TITLE
Resolution and Mobile

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#3]
As it stands now, the site will probably not really function below a certain browser size. What do we do for devices that are below that threshold? Just tell them to view it on the desktop?

Trying for a mobile optimized version would probably be a lot of additional work and potentially impossible? Last time I checked, the iPhone had no support for inline HTML 5 video, but that may have changed.

If we target a minimum resolution of 1024x768, I think it could still run on an iPad, though I don't know what performance would be like.

**Comment by REAS** [comment]
Good point. My first thought is that we don't need to consider phones, but it would be great to include tablets. As far as I know, tablets are used in schools now. If it's too difficult to support tablets, then let's not do it, but let's look into it. I think 1024 x 768 is the right decision for minimum res.

**Comment by scottgarner** [comment]
I'm pretty sure an iPad can handle inline video, so I think we'll be okay. The only other concern would be horrible Processing.js performance on older tablets, but we can see how that goes.

**Comment by scottgarner** [comment]
Just tested with a random Motorola Android tablet we had around. I fixed most of the glaring bugs, but a couple of things:

1) Usable height is probably going to be closer to 600px rather than 768px due to the browser and OS chrome.

2) On the particular tablet I was using, backspace was broken in Ace. I poked around a bit and this is a known issue, but difficult to trace because it only pops up in certain tablet/android/chrome combinations. Seemingly not an easy thing to fix. We could check it on the latest and greatest tablets and hope for the best.

3) Something should probably happen in portrait mode. Maybe a reconfiguration of the layout with the video and editor on top and the code window on the bottom? It won't be a great fit.

**Comment by scottgarner** [comment]
I think we're technically safe resolution-wise for an iPad, but I haven't done much functional testing because I don't have easy access to a tablet. I'm a little worried that some of the fancier functionality (like the color picker) isn't going to perform well. If anyone has a tablet, it would be good to start testing sooner rather than later.

**Comment by shiffman** [comment]
I'll test on an ipad.  Assigning this to me so I remember.   Feel the same way about this as browser support, due to limited resources I think we should not focus on this unless there are simple fixes.

**Comment by REAS** [comment]
These are the results of iPad testing. The video is extremely tiny in the upper left, the large video screen and welcome screen are pushed down about 200 pixels.

![img_20131110_071025](https://f.cloud.github.com/assets/677774/1510030/2937f006-4a6f-11e3-997d-fbe38ef60206.jpg)
![img_20131110_071048](https://f.cloud.github.com/assets/677774/1510032/293fc0ec-4a6f-11e3-8275-16b2bef43476.jpg)
![img_20131110_071036](https://f.cloud.github.com/assets/677774/1510031/293c4200-4a6f-11e3-8a22-b762e2e01abf.jpg)

**Comment by scottgarner** [comment]
Ah, thank you, Casey. Looks like the iPad is assuming a larger viewport than is actually there. I'll try the iPad simulator in Xcode for testing.

**Comment by REAS** [comment]
I wonder if it's because I'm running on an older, non-Retina iPad. I don't have a newer version to test on.

**Comment by shiffman** [comment]
@scottgarner i can lend you an ipad or I can ask Rob if we have one you can use (only if that is helpful and not distracting).  I also have an android tablet in my office I can crack open just out of curiosity.

**Comment by scottgarner** [comment]
Looks like the simulator has the same error, so I should be abel to debug from there and have it cover all iPads:

`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/`

**Comment by scottgarner** [comment]
I have things _mostly_ working in the iPad simulator, though I don't think anything we do is going to make this an ideal experience because of the craziness of the keyboard moving up and down whenever you need to type.

The biggest issue now is portrait mode, which needs either rearranged objects or a message to rotate your iPad.

**Comment by REAS** [comment]
I noticed that at 1024 width, the title of the page "Hello Processing" and the menu collide.

**Comment by scottgarner** [comment]
That's just from quickly adding the About and Guide links without any styling.

**Comment by scotthmurray** [comment]
I don't think this is just an iPad issue.  For me, the layout is broken in both Safari and Chrome on the desktop.  For example, go to this link:

http://hello.processing.org/editor/#shapes-9:30

Then see these screenshots from Safari:

![screen shot 2013-11-15 at 9 46 02 am](https://f.cloud.github.com/assets/1034002/1552063/59fab84c-4e1e-11e3-9119-07a09555b1f4.png)

…and Chrome:

![screen shot 2013-11-15 at 9 46 23 am](https://f.cloud.github.com/assets/1034002/1552065/5e501a2c-4e1e-11e3-87f7-f72bd92a66e5.png)

**Comment by scottgarner** [comment]
It's a slightly different but related issue. Once you leave landscape and approach square or portrait, the current layout has a problem because some ratios have to be maintained—the video width and height, for example.

There's not a great solution other than a bunch of conditionals in the layout function to accommodate square and portrait layouts. But no matter what, there's a size where things just won't fit anymore.

This is on my list and this issue will remain open until it's done, but Casey's specific iPad problem is fixed.

**Comment by scottgarner** [comment]
I've done work implement a constrained fluid layout. It also adds support of portrait view, though that makes @shiffman's references to the location of the canvas and editor incorrect. We may just decide to remove it because of this.

**Comment by scotthmurray** [comment]
Super. It still looks a little strange at some dimensions, but it looks great 99% of the time. Let's consider this layout issue fixed, and any other such adjustments can be low priority.  Thanks, Scott!

**Comment by REAS** [comment]
It's a great fix overall, Scott. I don't have an opinion on the portrait view yet.

**Comment by neave** [comment]
Currently there is a meta viewport tag preventing the site from being resized:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0,
minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi">
```

What are the implications of allowing the user to zoom out? That is, using this viewport definition instead:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0,
user-scalable=yes, target-densitydpi=device-dpi">
```

It would be a neat and simple solution that would allow mobile users to view the content without having to scroll around. But @shiffman mentioned that this caused issues with the app itself. Adding `event.preventDefault();` on touch events can help prevent scrolling on the appropriate interactive elements.

**Comment by neave** [comment]
Also, regarding @REAS' comment above:

> Good point. My first thought is that we don't need to consider phones...

I completely disagree, at least for the first-run experience. The first video could be very easily resized to fit into the screen width with a bit of CSS. After the first video, perhaps for now it should guide users to visit the site on desktop. But this is what a user sees when they first visit the site on an iPhone:

![img_7160](https://f.cloud.github.com/assets/129713/1634174/adb08a04-5795-11e3-9231-0977cffdfbc2.PNG)

We can do better :)

**Comment by scottgarner** [comment]
Thanks for the feedback, @neave. The fixed viewport was part of an earlier attempt to circumvent some display problems on the iPad. I've done some experimentation with the viewport so it will play a little more nicely with mobile devices and tablets, but for iPhones specifically the app simply will not work because videos cannot be played inline.

I've also been doing work on the layout handling to address some other bugs, so be on the lookout for other strangeness.

**Comment by neave** [comment]
Great stuff @scottgarner! It looks so much better on mobile now, nice work.

**Comment by scottgarner** [comment]
Thanks, @neave, and thanks for pointing out the problem.

**Comment by scottgarner** [comment]
Currently, the interface is fluid down to a size of 1024x540 at which point it locks. Instead of cutting off like it did in earlier versions, it can now scroll. There are definitely some compromises, but I think this is a good solution that should cover just about any sane use case. 

I'm going to close this issue and take some of the outstanding issues to #28 and #59.
