### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#30]
@shiffman brought this up in issue #21.

I'm a little ambivalent about the timer, though my instinct is that adding start/stop functionality complicates the interface and the interaction. I think it might make sense just to show it and assure the visitor that it's just a guide to keep them on track.

**Comment by REAS** [comment]
An alternate to a timer is a "teachers guide" that mentions how long to spend at each section. This way, it would be up to the room facilitator to say, "OK, time to move to lesson 3." I suppose this would require two links on each page: "About" and "Guide" I'm on the hook for writing about, so I could draft the guide as well.

I'm worried about the visible countdown timer in the long run, with people doing this at home in their own time.

**Comment by shiffman** [comment]
Agree with all points.  For now I am adding to the hints some language like so:

"You can work on your own pace, but we recommend approximately ten minutes on this assignment before moving on."

**Comment by scotthmurray** [comment]
Agreed with all comments above, as it's better to allow for self-paced exploration.

**Comment by scottgarner** [comment]
This sounds great. 

My only question, @REAS, is where you'd like to see these additional links and how you'd like them styled. I'd like to have them in place with basic content for the draft milestone this weekend.

**Comment by REAS** [comment]
I imagined it would be the same as issue #29, but now with two: "About" and "Guide." My first thought it to the right of "Goodbye" in the top header with a different type treatment or divider to distinguish them. Other ideas?

**Comment by shiffman** [comment]
For an example, check out the block.ly tutorial.

http://learn.code.org/hoc/1

Note how there is a progress bar on the top that indicates your progress.  This is this official hour of code tutorial and they are not holding anyone to a highly specific time so I think we are good with just estimates, suggestions, and a teacher's guide.

**Comment by REAS** [comment]
I checked it out and the progress bar is clear. I didn't see any timer data, though. Did I miss it?

**Comment by scottgarner** [comment]
I've added pages and rough links for Guide and About. These can be totally separate pages or they can open in some kind of overlay over the editor.

**Comment by shiffman** [comment]
@REAS, sorry if i wasn't clear, i meant that since the official hour of code tutorial is not using a timer but just making vague reference to time and showing a progress bar i think we can do the same and not feel so strict about it.

**Comment by scottgarner** [comment]
Closing this and opening a new issue specifically for the Teacher's Guide.
