### ISSUE TITLE
Video UI inconsistency

### ISSUE THREAD

**Issue by scotthmurray** [processing/Processing-Hour-Of-Code#31]
I notice that on all the videos except lesson 2, I don't see the Vimeo playback UI (play/pause button, timeline, volume).  Here's lesson 1:

![screen shot 2013-11-13 at 8 58 06 am](https://f.cloud.github.com/assets/1034002/1533405/08efb9ce-4c85-11e3-941b-1b23b29bc322.png)

Here's lesson 2:

![screen shot 2013-11-13 at 8 58 15 am](https://f.cloud.github.com/assets/1034002/1533406/0bd663fe-4c85-11e3-8fd2-98654b226ecf.png)

Shouldn't these be consistent?  Why is 2 different from the others?

**Comment by scottgarner** [comment]
This conversation is lost in some other thread, but we only turned it on for lesson 2 to ease editing. The idea is to disable it for all videos before launch.
