### ISSUE TITLE
Guide Page

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#34]
Page for teacher instructions. It will live at http://hello.processing.org/guide/ and be linked in the header.

Content goes in /guide/index.html. I'll work on the styling and layout if @REAS can handle the content.

**Comment by shiffman** [comment]
The new guide page looks great.   A few comments.

I think in the video lessons I refer to "Decisions" as "Questions".  This is actually a larger question . . should we revise this in the header of the site as well?

For interact, maybe we need to also say one sentence that we are moving from static to dynamic with setup() and draw().

Do we want to provide some small suggestions re: timing?   I am still not clear what to recommend in terms of doing this all in one hour. . seeing how long the videos end up being will help.

**Comment by REAS** [comment]
If you do talk about "Questions", then I think we should change both. Let me know or we'll see when we have the videos.

Will add your suggestion to Interact.

I can add timing notes to the Guide. As you mention, we need to see how the video plays out first.

**Comment by shiffman** [comment]
I think I said "Questions" as my topic for the fourth lesson, but I guess we'll have to wait and watch the videos to be sure!

**Comment by shiffman** [comment]
FYI, I added "background()" to the guide under quick reference.

**Comment by shiffman** [comment]
Decisions is now "Questions" everywhere on the site: 3eaa9b65a4947063daa2c4b9874eadf271108d0b

**Comment by shiffman** [comment]
I discovered this wonderful teacher's guide for the Khan Academy tutorial.  A great reference as we work to expand / update this page.

https://www.khanacademy.org/hour-of-code/hour-of-code-for-teachers/a/using-hour-of-code-in-your-classroom
