### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#35]
Page for background and credits. It will live at http://hello.processing.org/about/ and be linked in the header.

Content goes in /about/index.html. I'll work on the styling and layout if @REAS can handle the content.

**Comment by scottgarner** [comment]
Bringing the discussion back here:

@REAS, please feel free to chop up and edit the technologies section. Regarding your note on Processing.js, did that mean you wanted more than the half-sentence blurb I had in the frameworks paragraph? I'm glad to add more, but, again, please edit as you see fit.

Also, your last tweaks all look good, @alignedleft, except that `<tt>` is no longer valid in HTML5. `<kbd>` might be most valid in this instance? I'd probably just stick with `<code>`.

**Comment by REAS** [comment]
Great, thanks @scottgarner  and @alignedleft. The <tt> shenanigans were my old-fashioned ways. I replaced with <code> in both the About and Guide.

The body text for both pages should also be Thesis, as on Processing.org
