### ISSUE TITLE
Shapes annotation bug?

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#37]
Not sure why, but in the shapes video at about ~6:15, the code for the example pops up in the editor.  It goes away shortly after.  Looking through script.js don't see any obvious mistake that causes this.

http://hello.processing.org/editor/#shapes-6:10

**Comment by scottgarner** [comment]
My fault. I had already placed the code to load the example before I realized it wasn't mentioned in the video. I'll move it to come up with the hints window for now and the first pass at Shapes should be done.
