### ISSUE TITLE
Reset Code button isn't working

### ISSUE THREAD

**Issue by lmccart** [processing/Processing-Hour-Of-Code#39]
I tried several different code errors, each one pops up the Don't Panic box with the correct hint, the Continue button works but the Reset Code button doesn't.

Seeing error 'Uncaught TypeError: Cannot read property 'runCache' of undefined editor.js:163' in console.

(using chrome v31.0.1650.57)

**Comment by scottgarner** [comment]
I missed that call during a refactor of the caching system. Thanks Lauren!
