### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#4]
This is something I always forget about, so I thought I'd add it here now. If we want to use Google Analytics, I just need an account ID.

**Comment by scotthmurray** [comment]
Since this will be integrated into processing.org, I recommend we just extend whatever is already in use there.

**Comment by scottgarner** [comment]
I see a Google Analytics ID at processing.org, so I can definitely just grab that when we're ready go.

**Comment by scottgarner** [comment]
Just need to confirm that I can use the same ID from Processing.org or if a new one needs to be made.

**Comment by REAS** [comment]
I think we should use the same ID if it technically works.

**Comment by scottgarner** [comment]
It definitely isn't a technical problem. Using the same id just means that this subdomain appears in the same report as processing.org, but should still be discernible as a separate entity. I see, though, that www. and forums.processing.org appear to have different ids and are apparently tracked separately.

**Comment by REAS** [comment]
Thanks for the context. Let's use the same ID.
