### ISSUE TITLE
Two more links with About and Guide

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#41]
Help -- link to forum
Hour of Code -- link to hour of code completion page (?)

**Comment by shiffman** [comment]
I added the additional links but this messed up the layout on the about and guide pages. See: http://hello.processing.org/guide/  I'm happy to futz with the CSS but @scottgarner I assume you may have a preferred way to deal with this.

**Comment by REAS** [comment]
Also, the Hour of Code link currently goes to the "completion" page. Is that intentional or should it go to the main page?

**Comment by shiffman** [comment]
This was mostly by accident as I was making these changes quickly between classes.  

I just checked and the official hour of code tutorial has a link at the top that says "I've finished my Hour of Code" which you can click at any time (though I suppose you are meant to click it at the end.)   We could use the same language.  Or just provide a link to the main page.

**Comment by scottgarner** [comment]
This pretty much demands a width of at least 1024, so everything locks at that width now. Should be okay for instances we're worried about.
