### ISSUE TITLE
Hidden Run Code button?

### ISSUE THREAD

**Issue by lmccart** [processing/Processing-Hour-Of-Code#43]
I couldn't figure out how to run the code on the Interact and Questions section, should the run button be shown?

![screen shot 2013-11-26 at 10 38 14 am](https://f.cloud.github.com/assets/191056/1623181/eb4d02f6-56b0-11e3-9aec-b8d8010c5ccf.png)

**Comment by shiffman** [comment]
i have been trying to script all the buttons to appear and disappear, must have missed this one.  fixing now.

**Comment by shiffman** [comment]
closed via 1ab11af4de673122f5e096d870fe7fca920d3ed3
