### ISSUE TITLE
Clarify rulers design

### ISSUE THREAD

**Issue by scotthmurray** [processing/Processing-Hour-Of-Code#44]
I think two minor refinements would help clarify the coordinates system:

1)  Include a label for the origin point (0,0)
2)  Align ruler labels so they are flush with their corresponding markers.

Currently, the labels are a bit too far away from the markers for my tastes; it's a bit "floaty" and I could see this being confusing for someone new to coordinates:

![screen shot 2013-11-26 at 8 34 19 am](https://f.cloud.github.com/assets/1034002/1623804/9cff702c-56b8-11e3-85dc-646e6305fd3b.png)

Here's a mockup with my proposed changes.  Note that labels are flush with the markers (1px or 2px away) and vertically aligned with the top of the marker.

![rulers_mod](https://f.cloud.github.com/assets/1034002/1623781/5dd95728-56b8-11e3-98ca-739021607f8b.png)

If others agree this would help clarify things, then hopefully it's a simple change.

**Comment by scottgarner** [comment]
I bumped the numbers. Adding 0,0 in a tidy way would be non-trivial at this point.
