### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#47]
When we have time, we should add an option for captions so that the tutorial is more accessible.  

From @johnschimmel: "There might be services that could do this collectively like Amara, http://www.amara.org/en/"

**Comment by scottgarner** [comment]
Great idea. This is something we could potentially add very easily with Popcorn and the right closed captioning script.

**Comment by johnschimmel** [comment]
Awesome thanks guys! Also the Amara folks also offer translation/subtitles

**Comment by kritzikratzi** [comment]
as soon as there are english captions feel free to ping me and i can translate them to german.

**Comment by shiffman** [comment]
The videos have been captioned here:
1. Hello -- http://amara.org/en/videos/BxypnyB2TOeT/info/1-hello/
2. Shapes -- http://amara.org/en/videos/mbcnUKQTcQmU/info/2-shapes/
3. Color -- http://amara.org/en/videos/trcd6uBeOaIG/info/3-color/
4. Interact- http://amara.org/en/videos/vzQsMCCW505W/info/4-interact/
5. Questions -- http://amara.org/en/videos/54JSS6GrwbPf/info/5-questions/
6. Goodbye -- http://www.amara.org/en/videos/ESalwqP9TX4E/info/6-summary/

I guess the question is, it it trivial to embed these instead of vimeo?  Or perhaps we could export versions with the captions, upload to Vimeo and add an option to the site to load with captions or not?

**Comment by johnschimmel** [comment]
If still using Popcorn might be worth trying Popcorn JS SRT parser http://popcornjs.org/popcorn-docs/parsers/#SRT parser

Visit the video, click on the language available, English this will take you to the caption/subtitle page. There should be a download link for the .srt file. http://amara.org/en/videos/BxypnyB2TOeT/en/825595/

**Comment by scottgarner** [comment]
Neat! It looks like we can download the caption files straight from Amara
and add them to the repository (there doesn't seem to be a way to link
directly).

Vimeo does have an option for uploading caption files, but since we're not
using their player chrome in the site, I'm not sure how that would work.

I'll try to take a look this week and see if there's an easy way we can
drop them in. One of Popcorn's parsers is probably the way to go unless it
somehow interferes with the scripting we already have.

-S

**Comment by flatsiedatsie** [comment]
I work for a medialab called [SETUP](http://www.setup.nl) in the Netherlands. Last year we developed a [Dutch-language open-source creative coding course](http://www.appsomintelijsten.nl). There is a lack of Dutch-language creative-coding courses.

We would happily translate the subtitles for hello.processing.org into Dutch. It might also be interesting to re-create the videos in Dutch? In either case, contact us by emailing to info@ and then our website.

**Comment by scottgarner** [comment]
I've added basic support for English captions. Adding new languages later on would be relatively easy.

Currently, you just toggle captions on and off from the buttons that appear over the video. The toggle doesn't yet carry from one lesson to the next.

**Comment by flatsiedatsie** [comment]
Great. I've added Dutch subtitles to the first video, and am about to start on the second.

Is this useful? Will you be able to make a language toggle?

**Comment by flatsiedatsie** [comment]
I also noticed someone has dubbed the videos into Russian.
http://vimeo.com/91982680

**Comment by shiffman** [comment]
There's actually a full Russian port here: http://helloprocessing.ru/

**Comment by scottgarner** [comment]
@flatsiedatsie A Dutch translation would be great! I can switch the new toggle to a menu to select languages pretty easily.

**Comment by scottgarner** [comment]
Closing for now, but ready to reopen if there are new languages or tweaks to be made.

**Comment by ghost** [comment]
We(@p5-tr) would like to translate whole site into Turkish and publish our translation for free if this won't cause any licensing issues?

**Comment by scottgarner** [comment]
I don't see any problem with that at all. You could publish separately or if you wanted to add a language toggle to this site, that would be great, too. Sound okay, @shiffman?

**Comment by shiffman** [comment]
Indeed!
