### ISSUE TITLE
Audio is muted on Chrome, Windows 7.

### ISSUE THREAD

**Issue by paulmmay** [processing/Processing-Hour-Of-Code#48]
Hello. When I go to http://hello.processing.org and click "Click Here to Begin" the video loads and autoplays, but with no sound. I have checked the site in a different browser, and the sound is audible. I have checked my mixer and headphones. 

I think that videos that autoplay are automatically muted in some browsers. You might want to add volume controls, or somehow autoplay with audible sound.

Thanks.

**Comment by valhead** [comment]
I'm getting the same issue (video but no sound) with Chrome 31.0.1650.57 on OSX 10.8. It's kind of funny to watch like this, but I bet it's much better with sound :)

**Comment by studioijeoma** [comment]
I'm having the same issue in OSX 10.8.5 with Chrome 30.0.1599.101

**Comment by scottgarner** [comment]
Thanks for reporting, everyone. It seems that Vimeo wants to mute in certain cases. For me, I could mute a random video on Vimeo and then our player would be muted. 

Before playing any given lesson, I now force unmute and set the volume to full, which should hopefully take care of the problem.
