### ISSUE TITLE
Button for Next Tutorial at end of Shapes Chp Broken 

### ISSUE THREAD

**Issue by sheiva** [processing/Processing-Hour-Of-Code#51]
Using Safari, clicking on the play next tutorial button will restart the same chapter instead of starting the next chapter.

Thanks! Really enjoying this!

**Comment by shiffman** [comment]
I'm not able to reproduce this.  Tried in safari and chrome.  Are you sure it's the incorrect video?  They start in very similar ways.  Can you send more specific OS and browser info?

**Comment by sheiva** [comment]
Absolutely. I'm running Safari Version 6.0.2 and Mac OS X 10.7.5

Let me see if I can reproduce the issue now and I will report back.

**Comment by scottgarner** [comment]
@shiffman, I have a feeling this is related to the problem some people were seeing on Color where the examples weren't being displayed. Like the script between Shapes and Color isn't being parsed correctly?

What's difficult, I think, is that it isn't just going to be about the browser, it's going to be about the browser, the browser version and the version (or absence of Flash).

So far I haven't been able to reproduce any of the errors of this type. If I can make one happen, I can hopefully come up with a stopgap.

**Comment by sheiva** [comment]
I tried three different times and looks like I haven't been able to reproduce the error. Good news? Must have been a fluke.

Thanks for some great work! Cheers!

**Comment by scottgarner** [comment]
Thank you, Sheiva. 

If you do see anything else weird, you can quickly check the Safari console with COMMAND-OPTION-C for anything suspicious.
