### ISSUE TITLE
User code is erased whenever Dan adds code

### ISSUE THREAD

**Issue by sansumbrella** [processing/Processing-Hour-Of-Code#52]
This might be a boon, in case the user has written code that won't run, but it feels wrong to me.

To reproduce:
Write some code in the editor before Dan says he will add the rect() call for you. Your code is replaced by Dan's.

**Comment by shiffman** [comment]
Thanks for the feedback.   I can see the issue you are referring to.  We are capturing what the user creates at the end of each lesson with an option to restore at the end of the subsequent lesson but any little snippets written during the video itself are lost as soon as the popcorn events overwrite the editor text.

I'm not sure what we can do about this for the CSED week launch, but this is an interesting problem to think about for the future.  Will be curious to hear if we get complaints from users about this.

**Comment by sansumbrella** [comment]
I imagine most users (particularly new learners) won't be writing as much code as I while you talk. Worth watching to see if it does pose a problem for anyone else.

**Comment by scottgarner** [comment]
It's definitely not ideal, but this seemed to be the simplest solution rather than going for two editors/buffers and trying to switch back and forth without confusing the user.
