### ISSUE TITLE
Credit the featured projects on the About page

### ISSUE THREAD

**Issue by REAS** [processing/Processing-Hour-Of-Code#53]
Credit the featured project on the About page

**Comment by scottgarner** [comment]
Where available I grabbed whatever URL was referenced in the Processing Exhibition. In other cases I searched Google for whatever seemed to be the "canonical" project page.

Would you mind looking [these](http://hello.processing.org/about/) over, @shiffman?

**Comment by shiffman** [comment]
This looks perfect, thank you!  @REAS see anything we missed?  Closing for now, we can re-open if need be.

**Comment by REAS** [comment]
Goods good to me. :)
