### ISSUE TITLE
run button lost with browser zoom

### ISSUE THREAD

**Issue by willcanine** [processing/Processing-Hour-Of-Code#55]
if you zoom in, the run button gets cut off the bottom of the screen.

**Comment by scottgarner** [comment]
Thanks, Will.

It's a tricky thing with our fluid layout because the browser doesn't really tell you what's going on as things get bigger.

It tries to play a little more nicely with zoom now and even if the button does get cut off, you can now scroll the page and see it.

**Comment by willcanine** [comment]
Woohoo! so pro! :)
