### ISSUE TITLE
Scrollbars in Chrome

### ISSUE THREAD

**Issue by aengelke** [processing/Processing-Hour-Of-Code#56]
![image](https://f.cloud.github.com/assets/4236689/1648477/08596928-599c-11e3-8bef-df13d2c758e8.png)

![image](https://f.cloud.github.com/assets/4236689/1648480/1f14cd4c-599c-11e3-8f68-59080b33e9b7.png)

**Comment by scottgarner** [comment]
The interface should scroll now if it goes below a certain threshold, but definitely shouldn't have double bars like that. 

I can't reproduce it on my Mac, but made a CSS change that should fix it.
