### ISSUE TITLE
Code.org API 

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#57]
From code.org:

"API Information
Just a reminder (if you haven’t already done so) please include images on the first and last page of your Hour of Code tutorial. Please place a starting pixel-image on the start page and a final pixel-image on the end page - and not on interim pages."

I'm not sure the exact API specs and if there is online documentation, I'll write to code.org to find out.

**Comment by shiffman** [comment]
Related to this, I also changed the navbar link from "Hour of Code" to "I've finished my Hour of Code."    This is modeled exactly off of what the code.org official tutorial has (see: http://learn.code.org/hoc/1).

I don't know that this really works for us though.  Any thoughts?  I think we could:

a) keep as is
b) make it just say "Hour of Code" and link to http://code.org/learn
c) no link at all

**Comment by REAS** [comment]
I think a link that says "Hour of Code" and points to http://code.org/learn is best.

**Comment by shiffman** [comment]
Great, I reverted back to that.  19d0368e88fc3844c62aad9329a4cf1b89fa9865

**Comment by scottgarner** [comment]
We'll pull in the images via javascript since we don't really have separate pages. It should be simple enough once we have the URLs.

Do we start on the splash page or when the first lesson starts? Do we end on the final hints display or when the goodbye video starts?

**Comment by scottgarner** [comment]
Any updates here?

**Comment by shiffman** [comment]
Just got this finally.

http://code.org/api/hour/begin_processing.png
http://code.org/api/hour/finish_processing.png

**Comment by scottgarner** [comment]
Thoughts on the best start and end points?

**Comment by scottgarner** [comment]
@shiffman, currently I'm loading begin_processing.png at the beginning of the hello video and finish_processing.png at the beginning of the goodbye video.

Also, I'm a little worried I might have sloppily merged with your last commit, so you might want to check. Sorry about that.

**Comment by shiffman** [comment]
@scottgarner sounds perfect (beginning of hello, beginning of goodbye).  double-checked the merge, looks ok.  thanks!
