### ISSUE TITLE
iPad Interface Problems

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#59]
After testing in the Xcode simulator, we seem to be in fair shape on the iPad. I removed support for portrait mode because it just didn't work with Dan's cues.

Remaining issues have to do with interactions that depend on hover and on certain interactions accidentally opening the keyboard (clicking on the color "links", for example). I'm super pressed for time this week, but I may be able to take care of most of the problems with a few simple changes. 

Even with these things fixed, I definitely wouldn't consider it a recommended experience because the keyboard is such a problem.

**Comment by shiffman** [comment]
Ipad is working great for me, however, I'm getting some weird placement of the video.  

![img_0002](https://f.cloud.github.com/assets/191758/1693298/8783f444-5e8c-11e3-94d4-534a1d214851.jpg)
![img_0001](https://f.cloud.github.com/assets/191758/1693299/87d05082-5e8c-11e3-8212-177333adbc92.jpg)'

non retina ipad2, ios 7.0.3

anyone else have an ipad they can test on to see if this is a fluke on mine?

**Comment by scottgarner** [comment]
Weird! Everything seems fine in the simulator, but there's of course no guarantee that it performs the same on the real hardware.

I wonder if it's a caching problem? Can you clear your Safari cache from the Settings App under Safari -> Clear Cookies and Data.

**Comment by shiffman** [comment]
Didn't fix, and weirdly the videos are not auto-playing for me either.  There's a software update from apple, I'll give that a try and see if that fixes it.

**Comment by scottgarner** [comment]
I don't think you can auto play on iPad. 

—

**Comment by shiffman** [comment]
oh that makes sense, I think maybe I'll go and make sure I pick good thumbnails for the videos since they will appear on an ipad.

**Comment by scottgarner** [comment]
Any luck with the update? I've made a few minor tweaks, but am not sure it will make any difference. I think there are some layout bugs in mobile Safari that I don't see in the simulator.

**Comment by scottgarner** [comment]
iPad should be a bit more sane, but we still have the base problem that the keyboard sliding up makes the whole experience problematic.

I'm going to close this for now and will address specific issues as they crop up.
