### ISSUE TITLE
Share button highlighting?

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#60]
Going through the tutorial today I'm wondering if the share button is a bit too hidden.  I haven't noticed anyone using it (at least on twitter).   Should we reveal it sooner?  Should we highlight it more?

I added a script moment where I show it appear (http://hello.processing.org/editor/#goodbye-0:20) which may help a bit?

Thoughts?

**Comment by scottgarner** [comment]
Pointing it out in the script is the most straightforward thing we can do at this point. 

—

**Comment by shiffman** [comment]
Yes, I think this will help.  Let's "wait and see" what happens with csedweek and revisit this question later.  Will close for now.
