### ISSUE TITLE
Remove next lesson button from the last section.

### ISSUE THREAD

**Issue by aengelke** [processing/Processing-Hour-Of-Code#61]

**Comment by scottgarner** [comment]
The "Jump to End" button on the Goodbye Video? This was just added per #46.

**Comment by aengelke** [comment]
No, I mean the Next Lesson Button in the code window.

**Comment by scottgarner** [comment]
Whoops! Sorry about that. 

Should be removed.

**Comment by aengelke** [comment]
However, the run button is missing..
EDIT: No, it was just a caching issue...
