### ISSUE TITLE
Code buttons cover code in editor that can't scroll past

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#62]
A combination of browser dimensions and code length can cause a problem where the buttons to cover code and there is no way to scroll high enough to see / edit.  See screenshot:

![screen shot 2013-12-06 at 11 19 20 am](https://f.cloud.github.com/assets/191758/1693627/8220e308-5e92-11e3-80fb-afccdc989cba.png)

This is likely a very rare occurrence and not something we have to worry too much about -- after all it can be easily fixed by the user by adding some carriage returns.  So I don't think it's super critical.

**Comment by scottgarner** [comment]
I reside the editor so this shouldn't happen anymore.
