### ISSUE TITLE
Exit confirmation during all exercise sections

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#67]
Take the solution outlined in #63 and extend it to all exercise sections of the tutorial.

**Comment by scottgarner** [comment]
So the easy approach to this would be to flip on the exit confirmation anytime the editor is visible to avoid the weird problem of differentiating between scripted changes to the code and user changes.

It might annoy a few people that hadn't made changes, but wouldn't bother anyone during the videos themselves.

**Comment by shiffman** [comment]
Great, this seems to be working well.  I've tested it running through the tutorial and it seems more helpful than annoying.
