### ISSUE TITLE
Vimeo Player Issues

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#69]
Suddenly Popcorn seems to be having issues with Vimeo. I'm trying to figure out if it's something I broke or something that changed in the Vimeo Player, but even old commits seem broken.

I'm looking in to this, but we might end up having to switch to YouTube as a plan b.

**Comment by scottgarner** [comment]
Still no news on this. I've posted messages to both Popcorn and Vimeo, but the only responses have been from other people experiencing problems:

https://github.com/mozilla/popcorn-js/issues/417
https://vimeo.com/forums/api/topic:125223

**Comment by tdurand** [comment]
I have issue too, hope i'll be fixed soon

**Comment by scottgarner** [comment]
@shiffman I still have a feeling that this will work itself out soon, but just to be on the safe side and so that the site will work for now, we should probably upload the videos to YouTube. We can easily switch back to Vimeo when it becomes available.

The only real problem with YouTube is that there's no way to turn off the logo and we'd have to add our own pause/play button, which isn't that difficult. YouTube also loves to show videos at the lowest quality it can get away with and I'm not sure there's a great way around that without adding a quality button.

We also have the option of self hosting, but I'm not sure where we'd put them that would have the same fast distribution network as YouTube or Vimeo and still be free.

-S

**Comment by scottgarner** [comment]
Aha! Found a fix! It seems to be a bug in the new Vimeo player that's easy enough to work around. Details here:

mozilla/popcorn-js#417

**Comment by shiffman** [comment]
Awesome, so glad to hear this!  I tested and things seemed to be working now.  Hope your pull request gets merged!

**Comment by scottgarner** [comment]
Such a strange bug! I have a feeling that Vimeo will fix it before Popcorn does—development there seems stalled, which is a bummer.

Either way, I think we're in good shape, so I'll close this for now.
