### ISSUE TITLE
Hosting and URL

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#7]
I think we can start using `hello.processing.org` right away with the option to change at any time. Casey, you just need to [create a CNAME record](https://help.github.com/articles/setting-up-a-custom-domain-with-pages) that points to scottgarner.github.io.

Scott, you asked in an email about the gh-pages branch. We don't necessarily have to host the final site on GitHub, though that may be most convenient. We have to option to generate a static site and upload it to some other host, but I agree that if we do decide to host here it would be smart to have a development branch.

I haven't done that before in this context, but presumably we'd just have another CNAME in that branch and test from there. Something like `hello-dev.processing.org`.

**Comment by shiffman** [comment]
A minor point, but there is also a setting on github for "default branch" which we can change to "gh-pages" which i've found to be useful in cases like this.

**Comment by REAS** [comment]
`hello.processing.org` should be all set thanks to @benfry

**Comment by scottgarner** [comment]
Great! I updated the CNAME and the new URL should be working. I'll close this for now and we can open a new issue for hosting down the line if we need to.
