### ISSUE TITLE
tracking for 2016 Hour of Code

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#73]
Hi @scottgarner, we're back with this tutorial for 2016's Hour of Code.  Here are instructions we received.  I'm happy to implement this, but am wondering if you can provide a clue for best pinpointing the "end" of the tutorial.

> In order to more accurately track participation we ask every tutorial partner to include 1-pixel tracking images on the first and last page of their Hour ofCode tutorials. The starting pixel-image must be on the start page only and the finish pixel-image must be on the last page of your tutorial. Do not include either pixel on any interim pages of your tutorial.

> This will allow us to count users who do your Hour of Code tutorial. It will lead to more accurate participation counts for your tutorial. If you integrate the pixel at the end it will also allow us to measure tutorial completion rates.

> Here are the tracking pixels for your tutorial:

> IMG SRC = http://code.org/api/hour/begin_processing_foundation.png
> IMG SRC = http://code.org/api/hour/finish_processing_foundation.png

**Comment by scottgarner** [comment]
I'm pretty sure I have code in place to query an image at the start and end of the tutorial. (I can't remember how we determined the end, but at some point we did!) I'll take al look early next week because I think we just have to swap some URLs.

**Comment by shiffman** [comment]
@scottgarner awesome, thanks!  FYI, the deadline for this we've been given in Nov 15 (when they plan on testing the links).

**Comment by scottgarner** [comment]
I found the original commit for the image loading.

https://github.com/scottgarner/Processing-Hour-Of-Code/commit/a33a518ab4ba8c2c867663550dcb3f6e34f3e6b1#diff-2f86cb96a0233e7cb3b6f03ad573be0b

If you want to swap out the URLs, feel free. Otherwise I'll do it on Monday.

**Comment by shiffman** [comment]
All set now, thank you @scottgarner!
