### ISSUE TITLE
www.parsecdn.com no longer exists

### ISSUE THREAD

**Issue by beaumoaj** [processing/Processing-Hour-Of-Code#74]
The editor index.html contains this link: //www.parsecdn.com/js/parse-1.3.1.min.js
The server www.parsecdn.com no longer exists.
Where can I get this Javascript code from?

**Comment by shiffman** [comment]
Ah shucks! Parse.com has shut down. I would maybe suggest firebase as a replacement? @scottgarner do you have any other alternate recommendations?

**Comment by shiffman** [comment]
We could also run our own parse instance on maybe AWS or something?

**Comment by shiffman** [comment]
@scottgarner: @meiamsome and I are starting to work on a plan for updating this. What's the chance we might have a backup of the data anywhere? I think it's fine to start over but just curious.

**Comment by scottgarner** [comment]
Unfortunately it looks like Parse stopped allowing export when they shut down their servers on January 30, 2017.

**Comment by meiamsome** [comment]
Okay, I think that's everything - except for the _cloudcode folder - but as far as I can tell this doesn't do anything and can be deleted. Is this correct, @scottgarner ?

**Comment by scottgarner** [comment]
If I remember correctly, that stuff runs server-side on the Parse install. I think I was just using it for a view counter?

http://docs.parseplatform.org/cloudcode/guide/

You could almost certainly keep the same functionality without needing cloud code.

**Comment by meiamsome** [comment]
Ok, I have the view count implemented without it so I'll delete those files, and call this issue done!
